// ── Tactile Drive: Data Model ───────────────────────────────────
// Mock data for the library MVP. Pure data, no DOM/state here.

export const CATEGORIES = [
  { id: 'education', ko: '교육', icon: 'cap' },
  { id: 'science', ko: '과학', icon: 'flask' },
  { id: 'math', ko: '수학', icon: 'sigma' },
  { id: 'maps', ko: '지도', icon: 'map' },
  { id: 'culture', ko: '문화', icon: 'landmark' },
  { id: 'games', ko: '게임', icon: 'joystick' },
  { id: 'daily', ko: '생활', icon: 'house' },
  { id: 'art', ko: '미술', icon: 'palette' },
];
export const CAT_BY_ID = Object.fromEntries(CATEGORIES.map(c => [c.id, c]));

export const READINESS = {
  good: { label: '양호', var: '--green', bgVar: '--green-bg' },
  review: { label: '검토 필요', var: '--amber', bgVar: '--amber-bg' },
  complex: { label: '복잡함', var: '--red', bgVar: '--red-bg' },
};

export const COMPLEXITY = { low: '낮음', medium: '보통', high: '높음' };

export const FEATURED = [
  { id: 'recent', label: '최근 추가됨' },
  { id: 'dotpad6040', label: 'DotPad 60×40 준비 완료' },
  { id: 'teacher', label: '교사 추천 자료' },
  { id: 'agent', label: 'Tactile Agent 생성' },
  { id: 'verified', label: '검수 완료' },
];

export const AGENT_ACTIONS = [
  { id: 'simplify', label: '60×40 DotPad용으로 단순화', icon: 'scissors' },
  { id: 'describe', label: '촉각 설명 생성', icon: 'describe' },
  { id: 'worksheet', label: '학습지로 변환', icon: 'folder' },
  { id: 'declutter', label: '시각적 복잡도 줄이기', icon: 'sparkle' },
  { id: 'braille', label: '점자/음성 설명 만들기', icon: 'volume' },
  { id: 'check', label: '촉각 판독성 검사', icon: 'gauge' },
  { id: 'altversion', label: '저시력 아동용 대체 버전 생성', icon: 'heart' },
  { id: 'lowcomplex', label: '저복잡도 버전 생성', icon: 'layers' },
];

function makeAsset(a) {
  return {
    tags: [], formats: ['PNG'], resolutionSupport: ['60x40'],
    verified: false, dotPadTested: false, saved: false, landmarks: [],
    license: '교실 내 사용 허용 (CC BY-NC)',
    ...a,
  };
}

export const SEED_ASSETS = [
  makeAsset({ id: 'a1', title: '대한민국 지형도 — 산맥과 하천', category: 'maps',
    tags: ['지도', '지형', '산맥', 'korea', 'geography'], source: 'Tactile World',
    description: '한반도의 주요 산맥과 하천 줄기를 단순화한 촉각 지형도입니다.',
    tactileGuide: '왼쪽 위 모서리에서 시작해 굵은 윤곽선을 따라 해안선을 먼저 확인하세요.',
    landmarks: ['태백산맥 (오른쪽 세로선)', '한강 (중앙 가로선)', '동해안선'],
    recommendedUse: '중학교 사회 수업 · 지형 단원 도입부', ageLevel: '중학생 (13–15세)',
    complexity: 'medium', readinessScore: 'good', verified: true, dotPadTested: true,
    formats: ['SVG', 'PNG', 'DOTPAD'], resolutionSupport: ['60x40', '96x64'],
    createdBy: 'Tactile World 편집팀', updatedAt: '2026-06-18' }),
  makeAsset({ id: 'a2', title: '식물 세포 구조 단면도', category: 'science',
    tags: ['과학', '세포', '생물', 'biology', 'cell'], source: 'Tactile World',
    description: '세포벽·엽록체·핵을 구분한 식물 세포의 기본 단면 구조입니다.',
    tactileGuide: '가장 바깥의 이중 윤곽선이 세포벽입니다. 안쪽 큰 원이 핵이에요.',
    landmarks: ['세포벽 (겹선 테두리)', '핵 (중앙 큰 원)', '엽록체 (작은 타원 3개)'],
    recommendedUse: '고등학교 생명과학 I', ageLevel: '고등학생 (16–18세)',
    complexity: 'high', readinessScore: 'review', verified: false, dotPadTested: false,
    formats: ['PNG', 'PDF'], resolutionSupport: ['60x40'],
    createdBy: '김도윤 교사', updatedAt: '2026-06-22' }),
  makeAsset({ id: 'a3', title: '이차함수 그래프 — 포물선 기본형', category: 'math',
    tags: ['수학', '함수', '그래프', 'quadratic'], source: 'Tactile World',
    description: 'y = x² 기본형과 평행이동된 포물선을 나란히 배치한 그래프입니다.',
    tactileGuide: '가로·세로 축을 먼저 손끝으로 따라간 뒤 곡선의 최저점을 찾아보세요.',
    landmarks: ['원점 (교차점)', '포물선 최저점', 'x축 대칭선'],
    recommendedUse: '중학교 3학년 수학 · 이차함수 단원', ageLevel: '중학생 (14–15세)',
    complexity: 'low', readinessScore: 'good', verified: true, dotPadTested: true,
    formats: ['SVG', 'DOTPAD'], resolutionSupport: ['60x40', '96x64'],
    createdBy: 'Tactile World 편집팀', updatedAt: '2026-06-10' }),
  makeAsset({ id: 'a4', title: '촉각 미로 게임 — 초급', category: 'games',
    tags: ['게임', '미로', '놀이', 'maze'], source: 'Tactile Agent',
    description: 'Tactile Agent가 자동 생성한 8×8 초급 난이도 미로입니다.',
    tactileGuide: '왼쪽 아래 시작점에서 오른쪽 위 도착점까지 벽을 따라가세요.',
    landmarks: ['시작점 (별표)', '도착점 (사각형)'],
    recommendedUse: '쉬는 시간 촉각 놀이 활동', ageLevel: '초등학생 (8–10세)',
    complexity: 'low', readinessScore: 'good', verified: false, dotPadTested: true,
    formats: ['DOTPAD'], resolutionSupport: ['60x40'],
    createdBy: 'Tactile Agent', updatedAt: '2026-06-27' }),
  makeAsset({ id: 'a5', title: '우리 동네 지도 — 학교 주변', category: 'daily',
    tags: ['생활', '동네', '지도', '안전'], source: 'Tactile World',
    description: '학교를 중심으로 한 도보 통학로와 주요 건물을 표시한 생활 지도입니다.',
    tactileGuide: '가운데 큰 사각형이 학교입니다. 굵은 점선이 통학로예요.',
    landmarks: ['학교 (중앙 사각형)', '횡단보도 (점선 3곳)', '편의점 (작은 원)'],
    recommendedUse: '저학년 보행 안전 교육', ageLevel: '초등학생 (7–9세)',
    complexity: 'low', readinessScore: 'good', verified: true, dotPadTested: false,
    formats: ['PNG', 'PDF'], resolutionSupport: ['60x40'],
    createdBy: '서울맹학교 전공과', updatedAt: '2026-05-30' }),
  makeAsset({ id: 'a6', title: '훈민정음 반포 기록화 재구성', category: 'culture',
    tags: ['문화', '역사', '한글', 'heritage'], source: 'Tactile World',
    description: '훈민정음 반포 장면을 단순한 인물 배치로 재구성한 문화유산 그래픽입니다.',
    tactileGuide: '중앙 인물이 세종대왕입니다. 좌우로 신하들의 실루엣이 배치되어 있어요.',
    landmarks: ['세종대왕 (중앙 큰 실루엣)', '신하 4인 (좌우 작은 실루엣)'],
    recommendedUse: '한글날 기념 수업', ageLevel: '초등 고학년 (10–12세)',
    complexity: 'high', readinessScore: 'complex', verified: false, dotPadTested: false,
    formats: ['PNG'], resolutionSupport: ['96x64'],
    createdBy: '국립한글박물관 협력', updatedAt: '2026-05-12' }),
  makeAsset({ id: 'a7', title: '정물화 구도 연습 — 사과와 병', category: 'art',
    tags: ['미술', '정물', '구도'], source: 'Tactile World',
    description: '명암 대신 윤곽선 굵기로 원근을 표현한 정물화 촉각 버전입니다.',
    tactileGuide: '굵은 선일수록 가까이 있는 사물입니다. 병 → 사과 순으로 만져보세요.',
    landmarks: ['병 (왼쪽 큰 윤곽)', '사과 2개 (오른쪽 원)'],
    recommendedUse: '시각장애 학생 미술 감상 수업', ageLevel: '전 연령',
    complexity: 'medium', readinessScore: 'review', verified: false, dotPadTested: true,
    formats: ['SVG', 'PNG'], resolutionSupport: ['60x40'],
    createdBy: '이한나 디자이너', updatedAt: '2026-06-05' }),
  makeAsset({ id: 'a8', title: '분수 비교 막대 모델', category: 'math',
    tags: ['수학', '분수', '막대모델'], source: 'Tactile Agent',
    description: '1/2, 1/3, 1/4의 크기를 나란히 비교할 수 있는 막대 모델입니다.',
    tactileGuide: '위에서 아래로 막대 3개를 순서대로 비교하며 길이 차이를 느껴보세요.',
    landmarks: ['1/2 막대 (맨 위)', '1/3 막대 (가운데)', '1/4 막대 (맨 아래)'],
    recommendedUse: '초등 4학년 분수 도입', ageLevel: '초등학생 (10세)',
    complexity: 'low', readinessScore: 'good', verified: true, dotPadTested: true,
    formats: ['DOTPAD', 'SVG'], resolutionSupport: ['60x40', '96x64'],
    createdBy: 'Tactile Agent', updatedAt: '2026-06-29' }),
  makeAsset({ id: 'a9', title: '태양계 행성 크기 비교', category: 'science',
    tags: ['과학', '우주', '행성', 'solar system'], source: 'Tactile World',
    description: '8개 행성을 상대적 크기 순서로 배열한 촉각 다이어그램입니다.',
    tactileGuide: '왼쪽부터 태양에 가까운 순서입니다. 원의 크기로 행성 크기를 비교하세요.',
    landmarks: ['태양 (맨 왼쪽 큰 원)', '목성 (가장 큰 행성 원)', '수성 (가장 작은 원)'],
    recommendedUse: '초등 과학 · 태양계 단원', ageLevel: '초등 고학년 (11–12세)',
    complexity: 'medium', readinessScore: 'good', verified: true, dotPadTested: true,
    formats: ['SVG', 'DOTPAD', 'STL'], resolutionSupport: ['96x64'],
    createdBy: 'Tactile World 편집팀', updatedAt: '2026-06-14' }),
  makeAsset({ id: 'a10', title: '세계 지도 — 대륙 윤곽 단순화', category: 'maps',
    tags: ['지도', '세계', '대륙', 'world'], source: 'Tactile Agent',
    description: 'Tactile Agent가 실제 세계 지도 SVG를 60×40 해상도용으로 단순화한 버전입니다.',
    tactileGuide: '가운데 가로선이 적도입니다. 위쪽이 북반구예요.',
    landmarks: ['적도선 (중앙 가로선)', '아프리카 대륙', '유라시아 대륙'],
    recommendedUse: '세계지리 도입 수업', ageLevel: '중학생 이상',
    complexity: 'high', readinessScore: 'complex', verified: false, dotPadTested: false,
    formats: ['PNG'], resolutionSupport: ['60x40'],
    createdBy: 'Tactile Agent', updatedAt: '2026-06-24' }),
  makeAsset({ id: 'a11', title: '숫자 놀이판 1–20', category: 'games',
    tags: ['게임', '숫자', '놀이', '저학년'], source: 'Tactile World',
    description: '1부터 20까지 순서를 손끝으로 따라가는 저학년용 숫자 놀이판입니다.',
    tactileGuide: '왼쪽 위부터 지그재그로 1, 2, 3… 순서대로 배열되어 있습니다.',
    landmarks: ['시작 칸 (1번)', '도착 칸 (20번)'],
    recommendedUse: '촉각 숫자 감각 놀이', ageLevel: '유아 · 초등 저학년 (5–7세)',
    complexity: 'low', readinessScore: 'good', verified: true, dotPadTested: true,
    formats: ['DOTPAD'], resolutionSupport: ['60x40'],
    createdBy: 'Tactile World 편집팀', updatedAt: '2026-05-20' }),
  makeAsset({ id: 'a12', title: '명절 음식 상차림 배치도', category: 'culture',
    tags: ['문화', '명절', '음식', '생활'], source: 'Tactile World',
    description: '차례상의 기본 음식 배치를 촉각으로 익힐 수 있는 도식입니다.',
    tactileGuide: '가장 아래줄부터 위로 갈수록 상 앞쪽에서 뒤쪽 순서입니다.',
    landmarks: ['과일 줄 (맨 앞줄)', '전·적 줄 (가운데)', '밥·국 (맨 뒷줄 중앙)'],
    recommendedUse: '다문화·생활문화 이해 수업', ageLevel: '초등 전 학년',
    complexity: 'medium', readinessScore: 'review', verified: false, dotPadTested: false,
    formats: ['PNG', 'PDF'], resolutionSupport: ['60x40'],
    createdBy: '전통문화연구소', updatedAt: '2026-04-28' }),
  makeAsset({ id: 'a13', title: '동물 발자국 도감 — 숲속 동물 5종', category: 'science',
    tags: ['과학', '동물', '발자국', '생태'], source: 'Tactile Agent',
    description: '토끼·고라니·너구리 등 발자국 모양을 비교하는 생태 학습 자료입니다.',
    tactileGuide: '발자국 5개가 가로로 나열되어 있습니다. 크기 순으로 비교해보세요.',
    landmarks: ['토끼 발자국 (가장 작음)', '고라니 발자국 (중간)'],
    recommendedUse: '생태 체험 학습 사전 활동', ageLevel: '초등 저·중학년',
    complexity: 'low', readinessScore: 'good', verified: false, dotPadTested: true,
    formats: ['SVG', 'DOTPAD'], resolutionSupport: ['60x40'],
    createdBy: 'Tactile Agent', updatedAt: '2026-06-26' }),
  makeAsset({ id: 'a14', title: '기하 도형 이름 익히기', category: 'math',
    tags: ['수학', '도형', '기하'], source: 'Tactile World',
    description: '삼각형·사각형·오각형·육각형을 크기순으로 배열한 기초 도형 자료입니다.',
    tactileGuide: '왼쪽부터 변의 개수가 적은 순서로 배열되어 있습니다.',
    landmarks: ['삼각형 (맨 왼쪽)', '육각형 (맨 오른쪽)'],
    recommendedUse: '초등 2학년 도형 단원', ageLevel: '초등학생 (8세)',
    complexity: 'low', readinessScore: 'good', verified: true, dotPadTested: true,
    formats: ['DOTPAD', 'SVG'], resolutionSupport: ['60x40', '96x64'],
    createdBy: 'Tactile World 편집팀', updatedAt: '2026-06-02' }),
  makeAsset({ id: 'a15', title: '자화상 — 질감으로 표현한 얼굴', category: 'art',
    tags: ['미술', '초상', '질감'], source: 'Tactile Agent',
    description: '서로 다른 점 밀도로 얼굴의 명암 질감을 표현한 실험적 작품입니다.',
    tactileGuide: '점이 촘촘한 부분이 어두운 부분, 성긴 부분이 밝은 부분입니다.',
    landmarks: ['눈 (진한 점 두 곳)', '윤곽선 (얼굴 테두리)'],
    recommendedUse: '촉각 예술 감상 워크숍', ageLevel: '중·고등학생',
    complexity: 'high', readinessScore: 'complex', verified: false, dotPadTested: false,
    formats: ['PNG'], resolutionSupport: ['96x64'],
    createdBy: 'Tactile Agent', updatedAt: '2026-06-30' }),
  makeAsset({ id: 'a16', title: '물의 순환 다이어그램', category: 'science',
    tags: ['과학', '물의순환', '날씨'], source: 'Tactile World',
    description: '증발·응결·강수·유출 4단계를 화살표로 연결한 순환 다이어그램입니다.',
    tactileGuide: '화살표를 따라 시계방향으로 4단계를 순서대로 만져보세요.',
    landmarks: ['구름 (위쪽 왼쪽)', '비 (위쪽 오른쪽 점선)', '강 (아래쪽 물결선)'],
    recommendedUse: '초등 5학년 과학 · 물의 순환 단원', ageLevel: '초등 고학년',
    complexity: 'medium', readinessScore: 'good', verified: true, dotPadTested: true,
    formats: ['SVG', 'DOTPAD', 'PDF'], resolutionSupport: ['60x40', '96x64'],
    createdBy: 'Tactile World 편집팀', updatedAt: '2026-06-20' }),
];
